print "Hello world"
print "This is my first python Program"
print "I will print Few senseless lines "
print "I am an aspiring Machine learning student"
print "YO !"
print "USing Brackets for text editing "
print "Learn python the hard Way is the book"
print "Used for learning python"
print "Welcome to Vaibhavs world"
